##4.5cm marker
#LINEAR_THRESHOLD = 0.2
#ANGULAR_THRESHOLD = 0

#WEIGHT_LATERAL = 3.0
#WEIGHT_ALTITUDE = 5.0
#WEIGHT_DISTANCE = 1.8
#WEIGHT_ANGULAR_TURN = 2
#WEIGHT_ANGULAR_LATERAL = 2

#MIN_DISTANCE = 1
#MIN_HEIGHT = -0.2

##9cm marker
LINEAR_THRESHOLD = 0
ANGULAR_THRESHOLD = 0

WEIGHT_LATERAL = 1.8
WEIGHT_ALTITUDE = 3.0
WEIGHT_DISTANCE = 1.5
WEIGHT_ANGULAR_TURN = 2.5
WEIGHT_ANGULAR_LATERAL = 1.5

MIN_DISTANCE = 1.5
MIN_HEIGHT = -0.2